apiVersion: v1
kind: Service
metadata:
  name: getting-started-service
spec:
  selector:
    run: getting-started
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort
